# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4071a026579d2b89498c49aaa247a699"
name = "1106 Loyalty App Example"
handle = "1106-loyalty-app-example"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "1106mytestingstore.myshopify.com"
automatically_update_urls_on_dev = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
